# Comments '#' can be everywhere on the line, all subsequent chars will be ignored until '\n'.
# Spaces are not semantic (outside of key value separators) and can be either SP ot HTAB.
events {
	# the max number of simultaneous connections (client + server conections)
	# open sockets, Nginx use 2 connections at start
	max_connections 1024;
}

http {
	autoindex	false;

	# Errors and include paths are relative to the config file

	error_page	404		../html/error_pages/404_custom.html;

	keepalive_timeout	128;
	max_body_size	1048576;

	# root paths are relative to the executable
	root	html;

	# include raw file content (must be structured)
	include			mime.types; # fill 'types' block

	default_type	application/octet-stream;

	server {
		autoindex			true;
		listen				127.0.0.1:4242;
		storage	/storage/	storage;

		# root filesystem, absolute form or relative to server executable file
		root	html;

		location / {
			autoindex		true;
			cgi				false;
			index			index.html;
			limit_except	GET;
		}

		location = /src/dir1/ {
			autoindex true;
			index	index.html;
		}

		location /redirection/ {
			return	301 https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Accueil_principal;
			index	index.html;
		}

		location /redirection/redirection2/ {
			return	301 http://127.0.0.1:5252/;
			index	index.html;
		}

		location /src/ {
			autoindex true;
			index	src; # test redirection chain and autodindex
		}

		location /cgi/ {
			autoindex	true;
			cgi			true;
			cgi_nph		false;
			index		simple.sh;
		}
	}

	server {
		listen				127.0.0.1:5252;
		storage	/storage2/	storage2;
		autoindex			false;

		root 				html2;

		location /cgi/ {
			error_page	500	../html/error_pages/500_custom.html;
			cgi				true;
			cgi_nph			false;
			index			simple.py;
		}

		location /src/dir1/ {
			return	301		/; # redirection to /
			index			index.html;
		}

		# exact_match: wont enter if url != /src/dir1/dir2/ (/src/dir1/dir2/index.html will enter /src/dir1/)
		location = /src/dir1/dir2/ {
			index			index.html;
		}

		location / {
			index			index.html;
		}
	}
}

# vim: set ft=nginx:
